### PR TITLE
Use noarch, update homepage link.

### LINKED ISSUE #30: noarch support?
Can this package be defined as `noarch`? I'm running Linux on a POWER9 system (`ppc64le`) and it seems I can't install this package because it's only built for `linux-64`.

https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-builds

From what I can tell, this package adheres to the requirements for `noarch`. Anecdotally, I've found it's slightly easier to maintain conda-forge recipes that are `noarch`.

I can make a PR with this change if desired.

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #30 by adding noarch support.

### CODE REVIEW

**Comment by bdice** [comment]
@conda-forge-admin, please rerender.

**Comment by vidartf** [comment]
LGTM, but would appreciate a second opinion since I'm not super steady on the conda forge stuff :)

**Comment by SylvainCorlay** [comment]
After a quick look this looks ok since we dropped postlink scripts.

**Comment by vidartf** [comment]
@conda-forge-admin, please rerender

**Comment by vidartf** [comment]
@bdice I think the merge conflicts are due to the release that happened while this was waiting. Would you mind rebasing your branch? Sorry about the extra work 😞

**Comment by bdice** [comment]
@conda-forge-admin, please rerender! :)

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by bdice** [comment]
@vidartf Done! I rebased and rerendered on the latest release, so I think this is good to go. 👍

**Comment by vidartf** [comment]
Thanks!

**Pull request merged**
