### PR TITLE
Remove link scripts

### PR DESCRIPTION
**Pull request by vidartf**
Extensions install and enable by default with notebook >= 5.3

### CODE REVIEW

**Comment by jasongrout** [comment]
This means that it will need manual intervention for notebook < 5.3?

**Comment by jasongrout** [comment]
That means if your notebook is older than January, installing pythreejs now requires the enable step? Can I ask that we push the date out a bit further, especially since ipywidgets supports notebook 4 still?

Can we time the changes like this on packages with ipywidgets 8, probably sometime later this year, which may depend on notebook >=5.3?

**Comment by jasongrout** [comment]
I do think we should change the unlink scripts to use uninstall rather than disable, though.

**Comment by SylvainCorlay** [comment]
If we do this for pythreejs, we should do it for all widget libraries.

Quick note, we may remove the scripts and still formally support notebook 4, up to a manual enabling though.

**Comment by vidartf** [comment]
I'm concerned about the config state for users of notebook 5.3+:
 - a config file in the notebook.d folder is add/removed on install/uninstall.
 - that config is overridden by whatever these link scripts does.

If we simply remove these scripts, any user updating will:
1. run the unlink script on uninstall of the previous version
2. install the notebook.d config file, that gets overridden by the disabled config from the old unlink.

**Comment by vidartf** [comment]
That being said, I keep getting link failures on both install and uninstall of several widget packages (on Windows). E.g.:

```
WARNING conda.core.link:run_script(516): pre-unlink script failed for package conda-forge::widgetsnbextension-3.1.0-py36_0
```

The post-link script is also what is failing the 1.0 release in #12. I might be going overboard in saying the solution is to throw out the link scripts, but I don't really know what the actual issue is. If anybody does, I'm happy with a simple fix for now. Then we can revisit this PR when it is more appropriate to demand notebook 5.3 (we could consider putting that as a requirement for any conda packages that remove the link scripts, if that is more reasonable).

**Comment by jasongrout** [comment]
See also https://github.com/jupyter-widgets/ipywidgets/issues/1741 and https://github.com/conda-forge/widgetsnbextension-feedstock/issues/21

**Comment by jasongrout** [comment]
(Conclusion from conda-forge/widgetsnbextension-feedstock#21 is that conda fixed their bug, so upgrading conda fixes the issue there...)

**Comment by vidartf** [comment]
> so upgrading conda fixes the issue there...

Thanks! There's still the issue of why #12 is failing though. You mentioned something on gitter previously, but I never fully understood that 😅

**Comment by vidartf** [comment]
Punting

**Pull request closed without merging**
