### PR TITLE
Add ipydatawidgets requirement

### PR DESCRIPTION
**Pull request by vidartf**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

Add requirement on ipydatawidgets.

### CODE REVIEW

**Comment by vidartf** [comment]
@jasongrout I was thinking to merge this, then cycle #12 to pick this up from master. Is that a reasonable plan?

**Comment by jasongrout** [comment]
Does 0.4.1 depend on this? If not, I'm confused why you would merge this. If it does, then sure, the 0.4.1 package should be made correct.

**Comment by vidartf** [comment]
0.4.1 does not depend on it, but I'm also confused by the conda forge process. I thought it wouldn't rebuild 0.4.1 unless the build number was increased?

**Comment by SylvainCorlay** [comment]
It just seems that 1.0 has not been uploaded on conda forge and this is only 0.4.1

**Pull request closed without merging**
